[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy =  style-src 'self'; form-action 'self'; script-src 'self'; connect-src 'self'; img-src 'self';"