[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy =  style-src 'https://accounts.google.com/gsi/style';  script-src 'https://accounts.google.com/gsi/client'; connect-src 'https://accounts.google.com/gsi/';"